services:
  db:
    image: mariadb:10.3
    environment:
      MARIADB_DB: '{DBNAME}'
      MARIADB_ROOT_PASSWORD: '{DBPASSWORD}'
      MARIADB_ROOT_USER: '{DBUSER}'
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql
    
