services:
  db:
    image: mariadb:10.3
    environment:
      MARIADB_DB: '{DBNAME}'
      MARIADB_ROOT_PASSWORD: '{DBPASSWORD}'
      MARIADB_ROOT_USER: '{DBUSER}'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./diakkezelo-backend/db-data:/var/lib/mysql
    networks:
      - vpcbr
  
  backend:
    depends_on:
      db:
        condition: service_healthy
        restart: true
    image: diakkezelo-backend:latest
    ports:
      - "3000:3000"
    networks:
      - vpcbr
  
networks:
  vpcbr:
    driver: bridge
          
    
