services:
  db:
    image: mariadb:10.3
    environment:
      MARIADB_DB: '{DBNAME}'
      MARIADB_ROOT_PASSWORD: '{DBPASSWORD}'
      MARIADB_ROOT_USER: '{DBUSER}'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./diakkezelo-backend/db-data:/var/lib/mysql
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
  
  backend:
    depends_on:
      db:
        condition: service_healthy
        restart: true
    image: diakkezelo-backend:latest
    build: 
      context: ./diakkezelo-backend
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
  
  auth:
    depends_on:
      db:
        condition: service_healthy
        restart: true
    image: diakkezelo-auth:latest
    build: 
      context: ./diakkezelo-auth
    ports:
      - "3097:3097"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.7
  
  frontend:
    depends_on:
      - backend
      - auth
    image: diakkezelo-frontend:latest
    build: 
      context: ./diakkezelo-frontend
    ports:
      - "8080:80"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.8

  nginx:
    depends_on:
      - backend
      - db
      - auth
      - frontend
    image: nginx:latest
    container_name: nginx_container
    expose:
      - 3000
      - 80
      - 3097
    ports:
      - "127.0.0.1:80:80"
      - "3000:3000"
    volumes:
      - ./proxy-nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2
    

networks:
  vpcbr:
    driver: bridge
          
    
